name: 'Setup Node Env, Get & Cache Dependencies'
description: 'Setup Node Env, Get & Cache Dependencies(via yarn) for faster builds'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup node env 🏗
      uses: useblacksmith/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install Dependencies 👨🏻‍💻
      run: pnpm install --no-frozen-lockfile
      shell: bash
