import { NavigationBar } from '@/components/navigation-bar/navigation-bar'
import { auth } from '@/lib/auth'
import type { Metadata } from 'next'
import { headers } from 'next/headers'
import type { PropsWithChildren } from 'react'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<PropsWithChildren>) {
	const session = await auth.api.getSession({
		headers: await headers(),
	})

	return (
		<html lang="en">
			<body className="dark">
				<NavigationBar user={session?.user} />

				{children}
			</body>
		</html>
	)
}
